### ISSUE TITLE
Schema encoding does not recognize Schema.Transform and fails in runtime

### ISSUE THREAD

**Issue by pragmaxim** [zio/zio-jdbc#148]
Happens on master, at https://github.com/zio/zio-jdbc/commit/ce78cf036a1950f0534f57926c40e234e12af46f :

```
type Address = String Refined Base58Spec
object Address {
    extension (x: Address) def unwrapped: String = x
    def fromStringUnsafe(s: String): Address     = unsafeWrap(refineV[Base58Spec].unsafeFrom(s))
}
implicit val schema: Schema[Main] = {
   implicit val addressSchema: Schema[Address] = Schema.primitive[String].transform(Address.fromStringUnsafe, _.unwrapped)
   Schema.CaseClass22[.................](.............)
}
implicit val blockStatsDecoder: JdbcDecoder[Main] = JdbcDecoder.fromSchema
implicit val blockStatsEncoder: JdbcEncoder[Main] = JdbcEncoder.fromSchema

```

`Schema[Address]` is not recognized in `zio.jdbc.JdbcEncoder#fromSchema` as the pattern match does not deal with `zio.schema.Schema.Transform`.

```
Exception in thread "sbt-bg-threads-19" java.lang.ExceptionInInitializerError
        at backend.H2ZioBackend.main(H2ZioBackend.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at sbt.Run.invokeMain(Run.scala:143)
        at sbt.Run.execute$1(Run.scala:93)
        at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
        at sbt.Run$.executeSuccess(Run.scala:186)
        at sbt.Run.runWithLoader(Run.scala:120)
        at sbt.Defaults$.$anonfun$bgRunMainTask$7(Defaults.scala:1948)
        at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1919)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: zio.jdbc.JdbcEncoderError: Failed to encode schema Transform(Primitive(string,Chunk()), SourceLocation(/.../backend/package.scala,48,82))
        at zio.jdbc.JdbcEncoderError$.apply(JdbcEncoderError.scala:5)
        at zio.jdbc.JdbcEncoder0LowPriorityImplicits.fromSchema(JdbcEncoder.scala:694)
        at zio.jdbc.JdbcEncoder0LowPriorityImplicits.fromSchema$(JdbcEncoder.scala:638)
        at zio.jdbc.JdbcEncoder$.fromSchema(JdbcEncoder.scala:31)
        at zio.jdbc.JdbcEncoder0LowPriorityImplicits.caseClassEncoder$$anonfun$1$$anonfun$1(JdbcEncoder.scala:699)
        at zio.Chunk$Arr.mapChunk(Chunk.scala:1722)
        at zio.ChunkLike.map(ChunkLike.scala:121)
        at zio.ChunkLike.map$(ChunkLike.scala:39)
        at zio.Chunk.map(Chunk.scala:42)
        at zio.jdbc.JdbcEncoder0LowPriorityImplicits.caseClassEncoder$$anonfun$1(JdbcEncoder.scala:700)
        at zio.jdbc.SqlFragment.values$$anonfun$1(SqlFragment.scala:149)
        at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:75)
        at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:35)
        at zio.jdbc.SqlFragment.values(SqlFragment.scala:149)
        at zio.jdbc.SqlFragment.values$(SqlFragment.scala:33)
        at zio.jdbc.SqlFragment$FromFunction.values(SqlFragment.scala:401)
        at zio.jdbc.SqlFragment.values(SqlFragment.scala:162)
        at zio.jdbc.SqlFragment.values$(SqlFragment.scala:33)
        at zio.jdbc.SqlFragment$FromFunction.values(SqlFragment.scala:401)
```

**Comment by pragmaxim** [comment]
Ok, this will be probably closed by https://github.com/zio/zio-jdbc/issues/144
